### ISSUE TITLE
selectIndices error

### ISSUE THREAD

**Issue by stahlnow** [simdax/sonatinaSampler#1]
got error

```
Message 'selectIndices' not understood.
RECEIVER: [ c, c#, d, d#, e, f, f#, g, g#, a, a#, b ]
```

in the extractPitch method.

**Comment by simdax** [comment]
Hello, 

it's an old package, I fixed the issue, if you want to look at.

But I think you'll prefer check sfz-supercollider, which I forked too. It can read globally sfz libs.

**Comment by stahlnow** [comment]
@simdax thanks for the fix and hint!
